### PR TITLE
Added new achievements and fixed naming issue in achievement.go

### PR DESCRIPTION
**Pull request by antschni**
1. achievement.go: Added new achievements from TH15/Clan capital updates
2. achievement.go: Fixed name of achievement WellSeasoned
3. achievement.go: Ordered achievements the way they are displayed in Clash of Clans to make spotting missing achievements easier
4. achievement.go: Added json struct-tags to Achievement struct
5. clan.go: Removed unnecessary pointers from fields of Clan struct as they make the dev-experience worse
6. clan.go: Removed strings.ReplaceAll with builtin string slice to remove ```import "strings"```

### CODE REVIEW

**Comment by amaanq** [comment]
some of these changes are good, some not.

I believe the order was kept in line with achievement IDs, if you could just tack on th15 achievements at the end that'd be great. 

pointers are also used because the absence of a json key and the empty value are two different things, and should be treated as such. just because it's easier to use objects directly doesn't mean it's better. 

everything else is good to me

**Comment by amaanq** [comment]
thanks!

**Comment by antschni** [comment]
@amaanq Can you please create a new release to ```go get``` these changes?

**Comment by amaanq** [comment]
done

**Pull request merged**
